apiVersion  : apps/v1
kind        : Deployment
metadata:
  name: my-web.deplyment
  labels:
    app : my-nginx-application
spec: 
  selector:
    matchLabels:
      project: test
  template:
    metadata:
      labels:
        project: test
    spec:
      containers:
        - name  : test-web
          image : nginx:latest
          ports:
            - containerPort: 80  